# -*- coding: utf-8 -*-
"""Ejercicio Felipe Campos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVNxt9St8xU_8_8WsWkt7ozPsm6eFYk-
"""

alumnos={"nombre":input("Ingrese su nombre:"),
         "telefono":int(input("Ingrese su telefono:")),
         "correo":input("Ingrese su correo:"),
         "edad":int(input("Ingrese su edad:"))

}
while True:
  print("===MENÚ===")
  print("1.-Ver Ficha")
  print("2.-Editar dato")
  print("3.-Salir")
  opcion=int(input("Ingrese una opción:"))
  if opcion==1:
    print("===Ficha===")
    print("Nombre:",alumnos["nombre"])
    print("Telefono:",alumnos["telefono"])
    print("Correo:",alumnos["correo"])
    print("Edad:",alumnos["edad"])
    print("===========")
  elif opcion==2:
    print("¿Que campo desea editar?")
    print("Nombre")
    print("Telefono")
    print("Correo")
    print("Edad")
    editar=input("").lower()
    if editar=="nombre":
      alumnos["nombre"]=input("Ingrese el Nombre:")
      print("Nombre Cambiado, ahora el nombre es:",alumnos["nombre"])
    elif editar=="telefono":
      alumnos["telefono"]=int(input("Ingrese el Telefono:"))
      print("Telefono Cambiado, ahora el telefono es:",alumnos["telefono"])
    elif editar=="correo":
      alumnos["correo"]=input("Ingrese el Correo:")
      print("Correo Cambiado, ahora el correo es:",alumnos["correo"])
    elif editar=="edad":
      alumnos["edad"]=int(input("Ingrese la Edad:"))
      print("Edad Cambiada, ahora la edad es:",alumnos["edad"])
  elif opcion==3:
    print("===INFORMACION FINAL DEL ALUMNO===")
    print("Nombre:",alumnos["nombre"])
    print("Telefono:",alumnos["telefono"])
    print("Correo:",alumnos["correo"])
    print("Edad:",alumnos["edad"])
    print("===SALIENDO DEL SISTEMA===")
    break
  else:
    print("Opción Invalida")